[phases.setup]
nixPkgs = ["...", "maven"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[phases.start]
cmd = "java -Xmx512m -Xms256m -Dserver.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar"

[variables]
MAVEN_OPTS = "-Xmx512m"

